### ISSUE TITLE
Add User-Specific Rating Sort

### ISSUE THREAD

**Issue by horahoradev** [horahoradev/horahora#18]
## Context
Currently, Horahora supports sorting videos by views, ratings, or upload_date asc/desc. It would be nice if we added a sort by the individual user's ratings in order to preserve their list of preferred videos in the context of multiuser environments. This is a suitable task for beginners.

## Prerequisites
I'd recommend learning about the following topics before approaching this:
1. Golang (going through A Tour of Go is sufficient)
2. GRPC (reading the tutorial is fine, this is a basic usage)
3. SQL (some basic familiarity should be sufficient, but I may need to help here because this is complicated)
4. React (I used Frontend Masters when I was learning React, but I'm a shitty webdev so do what you feel is best)
5. (optional) docker and docker-compose (the basic tutorials are fine)

## Implementation
In order to get this working end-to-end, we need to touch three separate components: webapp (which is the React frontend), front_api (the RESTful API), and videoservice (which manages all videos).

### Webapp
Webapp interacts with the /api/home search API in order to display video lists. We need to add a  new category to the search dropdown in header.js , something like a value of "my_ratings".

### Front_api
The key function is the home route handler: https://github.com/horahoradev/horahora/blob/master/front_api/routes/GET_home.go#L25
This method is pretty shitty, maybe I should stop using URL query string params, but at any rate this method extracts three values from requests:
- the search string, which is a list of terms to filter by or exclude
- category, which is the category to order by
- order: ascending or descending, the order to sort by

There's an authentication middleware which validates the user's JWT cookie within front_api, and it sets a few attributes in the context, like "UserLoggedIn" becomes true if the JWT is valid, and it also sets a property for the UserID.
That middleware is here: https://github.com/horahoradev/horahora/blob/master/front_api/middleware/grpc_auth.go#L32

Within the home route handler, we first get the user's profile. This function abstracts a call to UserService which fetches the information for the userID set by the middleware. After we have their information, we check to see if they're privileged (rank >0), which means that they can see unapproved videos. Horahora has an approval workflow, in which newly downloaded videos are only visible to privileged users, and must be approved before being made available to regular users.

If they're privileged, it means showUnapproved = true, meaning that we can return unapproved videos to the user. Next, we get the videolist from Videoservice via GRPC. This happens here: https://github.com/horahoradev/horahora/blob/master/front_api/routes/GET_home.go#L84

What we actually need to change here: we need to update front_api's version of videoservice's protobuf GRPC definitions so that this line doesn't fail: https://github.com/horahoradev/horahora/blob/master/front_api/routes/GET_home.go#L55

### Videoservice
Videoservice handles everything relating to video storage and metadata. The GRPC API is defined by videoservice.proto. Specific to this task, we have the orderCategory enum, here: https://github.com/horahoradev/horahora/blob/master/video_service/protocol/videoservice.proto#L199
We'll need to modify that to add our new sort category, which is my_ratings (or similar). It needs to align with whatever we put as the value for the option, or it won't be found by front_api.

We also need to modify the SQL generation to sort by our new category. That code will come in the form of a new case here: https://github.com/horahoradev/horahora/blob/master/video_service/internal/models/video.go#L335
You'll add a new case handling the new my_ratings protobuf enum, which will order only by the user's ratings.
The problem here, and this is where it gets tricky, is that we need to do an inner join from ratings to the videos table within this case in order to just get the user's ratings. I'll probably need to help with that bit.

Schema stuff is in the migrations suibdirectory within each microservice (userservice, videoservice, scheduler). You'll definitely need to reference those files.

### Sequence of Implementation
Here's how I'd approach this:
1. Add new enum on videoservice proto definition
6. sudo ./gen_protos.sh (this igenerates the new protocol definitions)
7. stage, commit, push new definitions to your fork master
8. Add new case handling the new enum value to videoservice models/video.go, adding the new join and ordering
9. jump over to front_api, and change the version of its videoservice proto def: `go get github.com/<your github username>/horahora/videoservice@<whatever your last commit was>'
10. go mod vendor, see if it builds
11. Add the new dropdown value to the search component in headers.js
12. `sudo make up`, test it out end-to-end. You can also add a unit test to model_unit_tests.go , but it's been a while since I've used these.

**Comment by horahoradev** [comment]
This issue has been assigned to WhiffMerchant from Discord, whose Github I'm not aware of.

**Comment by ravihidayat** [comment]
Please assign this to me. -Whiff
