### ISSUE TITLE
Is it possible to transfer a copy of it to docker-hub?

### ISSUE THREAD

**Issue by zj1123581321** [horahoradev/horahora#39]
This project is great and will save me a lot of trouble in saving the video, thanks for developing and sharing it.

I tried to install it on unriad using docker compose, but it took 2 hours of searching trying... I finally got stuck at "sudo make up"

It was too hard for me, who doesn't have much programming knowledge, and I couldn't find any detailed information about horahora.

I don't know what to do next, it would be nice to find it in docker-hub.

![image](https://user-images.githubusercontent.com/33171229/171855964-1e11e1fb-fbcb-4d42-838c-798644524a0b.png)

**Comment by horahoradev** [comment]
I could, but you'd still need make in this case. I'll dedicate some time later to helping you install.

**Comment by horahoradev** [comment]
sorry, I spent 12 hours on the video download progress feature (it works now though) so I'm too exhausted.

I will do this tomorrow, first thing, if you're still around.

**Comment by zj1123581321** [comment]
Thank you very much, I am not in a hurry, just take your time：)

**Comment by horahoradev** [comment]
Removed make on master, try now.

**Comment by zj1123581321** [comment]
Thank you for your time.
I reattempted the install and this time it prompted `envsubst: command not found`.

I tried searching for a way to fix this, and [here](https://stackoverflow.com/questions/33548530/envsubst-command-getting-stuck-in-a-container) I tried installing envsub on unraid via npm, but it didn't work.

Any suggestions?
![image](https://user-images.githubusercontent.com/33171229/172200598-cae1277f-32af-47c4-806e-aab595922038.png)

**Comment by horahoradev** [comment]
I'll work on removing envsubst as an external dependency as well.

**Comment by horahoradev** [comment]
in the meantime, you should be able to install gettext or similar on your platform.

**Comment by horahoradev** [comment]
alright, going to work on this today.

**Comment by horahoradev** [comment]
https://github.com/horahoradev/horahora/releases/tag/v0.1.1

try now

**Comment by zj1123581321** [comment]
> in the meantime, you should be able to install gettext or similar on your platform.

Thanks for your time, I found the solution - To install [Devpack](https://github.com/dmacias72/unRAID-DevPack) at unraid to install gettext : )

**Comment by horahoradev** [comment]
Sure. Ping me if you have any further issues.
