### ISSUE TITLE
react_app container crashes with `/bin/sh: craco: not found`

### ISSUE THREAD

**Issue by ganrmit** [horahoradev/horahora#40]
Just trying to get started. After `sudo make up` docker logs are showing `react_app_1` crashing as craco can't be found. Log looks like:
```
react_app_1     | yarn run v1.22.19
react_app_1     | $ craco start
react_app_1     | /bin/sh: craco: not found
react_app_1     | error Command failed with exit code 127.
react_app_1     | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This seems like a problem in one of the images you rely on but if you can't reproduce it let me know what more details I can give.

**Comment by horahoradev** [comment]
I can reproduce it. Fix is within my PR, let me just push this to master...

**Comment by horahoradev** [comment]
pushed, try that

**Comment by ganrmit** [comment]
Works. Thank you for your effort.

**Comment by horahoradev** [comment]
Sure. ping me on discord, or raise another issue if you encounter any other problems.
