### ISSUE TITLE
Can't clone the repo

### ISSUE THREAD

**Issue by BassOfBass** [horahoradev/horahora#7]
First it starts with these errors:
```
error: invalid path 'front_api/routes/GET_comments_:id.go'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

```

When trying to run `git restore --source=HEAD :/`:
```
$ git restore --source=HEAD :/
error: invalid path 'front_api/routes/GET_comments_:id.go'
error: invalid path 'front_api/routes/GET_tag_:tag.go'
error: invalid path 'front_api/routes/GET_users_:id.go'
error: invalid path 'front_api/routes/GET_videos_:id.go'
error: invalid path 'front_api/routes/POST_approve_:id.go'
error: invalid path 'front_api/routes/POST_rate_:id.go'
```
Looks like OS doesn't like colons in the path.

Running on Windows 7.

**Comment by horahoradev** [comment]
That sounds like it would be a filesystem issue... I guess I could rename those files.

**Comment by BassOfBass** [comment]
Yeah, it's better not to use anything beyond lowercase english letters and underscore/hyphen for space in file paths in repos, since unix/windows have different opinions on them.

**Comment by horahoradev** [comment]
I pushed to master. Pull and try again.
